### ISSUE TITLE
Copy to clipboard or Navigate to DataContext or Target Classes.

### ISSUE THREAD

**Issue by finlaybob** [spadapet/xaml-binding-tool#6]
Firstly - this is a great little tool :) awesome work!

Then came the realisation that there is no way to copy the name of the DataContext class name or  Target class name. I'm having to go back to the debug output to C+P the class names.

Having a link to the classes would be even better but that's might be another task for another day.

Cheers

**Comment by spadapet** [comment]
Good one. I just published an update that switches from using the built-in WPF list view to the Visual Studio error pane's table control. Since the error pane allows copy/paste of column text, I assume I can fairly easily add in a similar context menu and Ctrl-C support.

Having a link to the class is a task for another day, and it's something I'm thinking about. Like if there's only one class in the project that matches the name, go to it.

**Comment by spadapet** [comment]
Turns out Ctrl-C works by default, so it'll copy all selected rows along with column headers. But there should be a context menu with "Copy" and the option to copy any individual value.

**Comment by spadapet** [comment]
Commit 9a896e36bed258908334c086924d3772c13397f0

Added a context menu for selected rows:
![image](https://user-images.githubusercontent.com/2523431/68318957-66408e80-0072-11ea-9e65-5b385352c7d9.png)

I'll log a new issue for navigating to code on double-click/enter. I'm not exactly sure how that's going to work, so it needs some thought. Going to the data context class isn't always right since you'd usually want to fix the {Binding} in XAML. But the output text gives no clue on the source XAML file or line, only the property name. That's a nice clue though.
